# Copyright 2025 Sascha Willems
# SPDX-License-Identifier: CC-BY-4.0
# This Antora playbook is used by the CI to make sure the Antora build works

site:
  title: Vulan Guide Antora CI Playbook
  start_page: guide::index.adoc
content:
  sources: 
  - url: ./
    branches: HEAD
    start_path: antora
ui: 
  bundle:
    url: ui-bundle.zip